"""add stocks

Revision ID: 20890ac1d32a
Revises: e8fe1da1b77b
Create Date: 2024-01-31 02:27:44.592125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20890ac1d32a'
down_revision = 'e8fe1da1b77b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastChangeDate', sa.TIMESTAMP(), nullable=True),
    sa.Column('warehouseName', sa.String(), nullable=True),
    sa.Column('supplierArticle', sa.String(), nullable=True),
    sa.Column('nmId', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('inWayToClient', sa.Integer(), nullable=True),
    sa.Column('inWayFromClient', sa.Integer(), nullable=True),
    sa.Column('quantityFull', sa.Integer(), nullable=True),
    sa.Column('techSize', sa.String(), nullable=True),
    sa.Column('Price', sa.Float(), nullable=True),
    sa.Column('Discount', sa.Float(), nullable=True),
    sa.Column('isSupply', sa.Boolean(), nullable=True),
    sa.Column('isRealization', sa.Boolean(), nullable=True),
    sa.Column('SCCode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
