"""add warehouses

Revision ID: 42163e9a2182
Revises: f853fc462574
Create Date: 2025-04-21 17:42:20.401028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42163e9a2182'
down_revision = 'f853fc462574'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boxDeliveryAndStorageExpr', sa.String(length=800), nullable=False),
    sa.Column('boxDeliveryBase', sa.String(length=800), nullable=False),
    sa.Column('boxDeliveryLiter', sa.String(length=800), nullable=False),
    sa.Column('boxStorageBase', sa.String(length=800), nullable=False),
    sa.Column('boxStorageLiter', sa.String(length=800), nullable=False),
    sa.Column('warehouseName', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
