"""add localization to user

Revision ID: 74765433ad1a
Revises: 9fc9083e2752
Create Date: 2025-04-03 01:49:14.497721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74765433ad1a'
down_revision = '9fc9083e2752'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('localization_index', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('localization_percentage', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'localization_percentage')
    op.drop_column('users', 'localization_index')
    # ### end Alembic commands ###
