"""company name

Revision ID: 77b8a2e473e7
Revises: 20890ac1d32a
Create Date: 2024-02-04 19:47:14.469652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b8a2e473e7'
down_revision = '20890ac1d32a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo', 'company_name')
    # ### end Alembic commands ###
