"""add warehouse type

Revision ID: 8673f25b8a38
Revises: d7ac0453e19a
Create Date: 2024-11-06 13:02:54.033141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8673f25b8a38'
down_revision = 'd7ac0453e19a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('warehouseType', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'warehouseType')
    # ### end Alembic commands ###
