"""create promo stats orderSUm 

Revision ID: 92ea312d9895
Revises: b0cf7e6d758a
Create Date: 2024-01-30 02:29:28.079677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ea312d9895'
down_revision = 'b0cf7e6d758a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_stats', sa.Column('date_order_sum', sa.Float(), nullable=True))
    op.add_column('promo_stats', sa.Column('drr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_stats', 'drr')
    op.drop_column('promo_stats', 'date_order_sum')
    # ### end Alembic commands ###
