"""add competitors

Revision ID: 9fc9083e2752
Revises: f0a151daba0d
Create Date: 2025-04-03 01:16:17.152471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc9083e2752'
down_revision = 'f0a151daba0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_nmID', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_id'), 'competitor', ['id'], unique=False)
    op.create_table('competitor_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_prices_id'), 'competitor_prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_prices_id'), table_name='competitor_prices')
    op.drop_table('competitor_prices')
    op.drop_index(op.f('ix_competitor_id'), table_name='competitor')
    op.drop_table('competitor')
    # ### end Alembic commands ###
