"""add avg_price

Revision ID: a1ac5f8652f9
Revises: d3f6eea685f2
Create Date: 2024-02-07 17:22:24.466482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ac5f8652f9'
down_revision = 'd3f6eea685f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('avg_price_rub', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'avg_price_rub')
    # ### end Alembic commands ###
