"""add product demensions

Revision ID: ac8c5a4db4a1
Revises: 42163e9a2182
Create Date: 2025-04-22 16:32:49.344591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8c5a4db4a1'
down_revision = '42163e9a2182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'height')
    op.drop_column('products', 'width')
    op.drop_column('products', 'length')
    # ### end Alembic commands ###
