"""create promo stats

Revision ID: b0cf7e6d758a
Revises: c8131acbfffb
Create Date: 2024-01-30 02:22:59.093463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cf7e6d758a'
down_revision = 'c8131acbfffb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo',
    sa.Column('advertId', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('advertId')
    )
    op.create_table('promo_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Integer(), nullable=True),
    sa.Column('cpc', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('nmId', sa.Integer(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('advert_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advert_id'], ['promo.advertId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_stats_id'), 'promo_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_stats_id'), table_name='promo_stats')
    op.drop_table('promo_stats')
    op.drop_table('promo')
    # ### end Alembic commands ###
