"""key word stat

Revision ID: d3f6eea685f2
Revises: 77b8a2e473e7
Create Date: 2024-02-04 20:25:26.387565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f6eea685f2'
down_revision = '77b8a2e473e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_words_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Integer(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('advert_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advert_id'], ['promo.advertId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_words_stats_id'), 'key_words_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_words_stats_id'), table_name='key_words_stats')
    op.drop_table('key_words_stats')
    # ### end Alembic commands ###
