"""stocks user

Revision ID: d7ac0453e19a
Revises: a1ac5f8652f9
Create Date: 2024-02-14 13:37:17.004919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ac0453e19a'
down_revision = 'a1ac5f8652f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stats', 'users', ['user_id'], ['id'])
    op.add_column('stocks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stocks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_column('stocks', 'user_id')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_column('stats', 'user_id')
    # ### end Alembic commands ###
