"""add product foreuing key

Revision ID: dd20b09315d2
Revises: 74765433ad1a
Create Date: 2025-04-03 02:37:02.723753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd20b09315d2'
down_revision = '74765433ad1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    op.add_column('promo_stats', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'promo_stats', 'products', ['product_id'], ['id'])
    op.add_column('stats', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stats', 'products', ['product_id'], ['id'])
    op.add_column('stocks', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stocks', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_column('stocks', 'product_id')
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_column('stats', 'product_id')
    op.drop_constraint(None, 'promo_stats', type_='foreignkey')
    op.drop_column('promo_stats', 'product_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###
