"""add product

Revision ID: f0a151daba0d
Revises: 8673f25b8a38
Create Date: 2025-04-03 00:34:20.526636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a151daba0d'
down_revision = '8673f25b8a38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_article', sa.String(), nullable=True),
    sa.Column('wb_article', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('wb_price', sa.Float(), nullable=True),
    sa.Column('fake_wb_price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('commision_percentage', sa.Integer(), nullable=True),
    sa.Column('logistics_fee', sa.Float(), nullable=True),
    sa.Column('tax_fee_percentage', sa.Float(), nullable=True),
    sa.Column('mono_items', sa.Integer(), nullable=True),
    sa.Column('box_items', sa.Integer(), nullable=True),
    sa.Column('demand', sa.Integer(), nullable=True),
    sa.Column('warehouse_amount', sa.Integer(), nullable=True),
    sa.Column('shipping_amount', sa.Integer(), nullable=True),
    sa.Column('production_amount', sa.Integer(), nullable=True),
    sa.Column('wb_warehouse_amount', sa.Integer(), nullable=True),
    sa.Column('plan_pallet', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
