"""add tax to user

Revision ID: f853fc462574
Revises: dd20b09315d2
Create Date: 2025-04-03 18:09:35.512678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f853fc462574'
down_revision = 'dd20b09315d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tax_fee_percentage')
    op.add_column('users', sa.Column('tax', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tax')
    op.add_column('products', sa.Column('tax_fee_percentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
